apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: Roboshop
    tier: db
    component: rabbitmq
    service:  headlessservice
spec:
  selector:
    project: Roboshop
    tier: db
    component: rabbitmq
  ports:
  - port: 5672
    name: rabbitmqHeadlessServicePort
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  namespace: roboshop
  labels:
    project: Roboshop
    tier: db
    component: rabbitmq
    service:  statefulset
spec:
  selector:
    matchLabels:
      project: Roboshop
      tier: db
      component: rabbitmq
  serviceName: rabbitmq-headless
  replicas: 1
  template:
    metadata:
      labels:
        project: Roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "roboshop"
            - name: RABBITMQ_DEFAULT_PASS
              value: "roboshop123"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          ports:
            - containerPort: 5672
              name: rabbitmqcontainerport
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
          # startup probe
          startupProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          # liveness probe
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          # Readiness Probe
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - check_running
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2

  # Volume template
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-volume
        namespace: roboshop
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-gp3-sc"
        resources:
          requests:
            storage: 1Gi