name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: roboshop/mongodb # docker build -t joindevops/mongodb:4.0.0
    container_name: mongodb # docker run -d --network roboshop joindevops/mongodb:4.0.0
    volumes:
    - mongodb:/data/db # mongodb stores data in /data/db directory
  catalogue:
    build: ./catalogue
    image: roboshop/catalogue
    container_name: catalogue
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: roboshop/frontend
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - user
    - catalogue
  redis:
    build: redis:7
    image: roboshop/redis
    container_name: redis
  user:
    build: ./user
    image: roboshop/user
    container_name: user
    depends_on:
      - redis
      - mongodb
  cart:
    build: ./cart
    image: roboshop/cart
    container_name: cart
    depends_on:
      - redis
      - catalogue
  

networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network

volumes:
  mongodb: # docker volume create mongodb