apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: Roboshop
    tier: db
    component: mysql
    service:  headlessservice
spec:
  selector:
    project: Roboshop
    tier: db
    component: mysql 
  ports:
  - port: 3306
    name: mysqlHeadlessServicePort
  clusterIP: None 

---
apiVersion: v1
kind: Secret
metadata:
  name : secretmapvalues
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9ib3Nob3BAMQ==
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql-statefulset
  namespace: roboshop
  labels:
    project: Roboshop
    tier: db
    component: mysql
    service:  statefulset
spec:
  selector:
    matchLabels:
      project: Roboshop
      tier: db
      component: mysql
  serviceName:   mysql-headless
  replicas: 1
  template:
    metadata:
      labels:
        project: Roboshop
        tier: db
        component: mysql
    spec:
      containers:
        - name: mysql
          image: sravan9661/roboshop-mysql:4.0.0
          envFrom:
          - secretRef:
              name: secretmapvalues
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 1
              memory:  1Gi
          ports:
            - containerPort: 3306
              name: mysqlcontainerport
          volumeMounts:
            - name: mysql-volume
              mountPath:  /var/lib/mysql 
          # startup probe
          startupProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          # liveness probe
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          # Readiness Probe
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2

  # Volume template
  volumeClaimTemplates:
    - metadata:
        name: mysql-volume
        namespace: roboshop
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ebs-gp3-sc" 
        resources:
          requests:
            storage: 1Gi
        

      
