- name: various methods of using vars 
  hosts: user
  vars:
    fullname: "Sravan"
    age: 26
    married: false
  tasks:
    - name: vars in task
      vars:
        fullname: "Mahesh Babu"
    - name: print info 
      debug:
        msg: "hi, this is {{fullname}},im {{age}} old, married {{married}}"