- name: variables declared in another file
  hosts: user
  connection: local
  vars_files:
    - variable.yaml
  tasks:
    - name: print info  
      debug:
        msg: "Hi,i'm {{fullname}},i'm {{age}}old, married {{married}}"